Repository FI18-Trainees/vvspy, pull requests merged in 2019-12, with the labels that each got.

#14 added codeowners
  .github/CODEOWNERS
  src/__init__.py
Labels: documentation

#15 basic oop fixes #13 fixes #1
  src/departures.py
  src/obj/trip.py
  src/test.json
  vvs/__init__.py
  vvs/departures.py
  vvs/obj/__init__.py
  vvs/obj/arrival.py
  vvs/obj/departure.py
  vvs/obj/line_operator.py
  vvs/obj/serving_line.py
  vvs/obj/trip.py
  vvs/trip.py
Labels: documentation, enhancement

#16 Pypi
  .gitignore
  MANIFEST.in
  readme.md
  requirements.txt
  setup.cfg
  setup.py
  vvs/__init__.py
  vvspy/__init__.py
  vvspy/departures.py
  vvspy/obj/__init__.py
  vvspy/obj/arrival.py
  vvspy/obj/departure.py
  vvspy/obj/line_operator.py
  vvspy/obj/serving_line.py
  vvspy/obj/trip.py
  vvspy/trip.py
Labels: documentation, enhancement

#17 bumped vvs api version, fixed import for dev env
  vvspy/departures.py
Labels: bug

#19 Create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: github

#21 added easy2use function and custom request params
  readme.md
  vvspy/__init__.py
  vvspy/departures.py
  vvspy/trip.py
Labels: documentation, feature

#22 documentation and minor changes
  readme.md
  setup.py
  vvspy/__init__.py
  vvspy/departures.py
  vvspy/obj/trip.py
Labels: documentation

#23 added examples/docu and fixed minor bugs
  readme.md
  setup.py
  vvspy/obj/departure.py
Labels: bug, documentation, feature

#27 added arpiix as codeowner
  .github/CODEOWNERS
Labels: github

#25 added trip request support
  readme.md
  setup.py
  vvspy/__init__.py
  vvspy/departures.py
  vvspy/obj/connection.py
  vvspy/obj/departure.py
  vvspy/obj/destination.py
  vvspy/obj/line_operator.py
  vvspy/obj/origin.py
  vvspy/obj/transportation.py
  vvspy/obj/trip.py
  vvspy/trip.py
Labels: documentation, feature

#28 minor changes in readme
  readme.md
Labels: documentation

#29 removed wip from readme
  .github/CODEOWNERS
  readme.md
  setup.py
Labels: documentation, github

#31 fixed readthedocs bug
  docs/source/conf.py
Labels: bug, documentation

#35 improved docs and one format for string outputs
  docs/source/help.rst
  readme.md
  setup.py
  vvspy/obj/arrival.py
  vvspy/obj/departure.py
Labels: documentation

#36 fixes #34
  vvspy/obj/arrival.py
  vvspy/obj/connection.py
  vvspy/obj/departure.py
Labels: feature

#37 Documentation
  docs/source/apireference.rst
  docs/source/conf.py
  docs/source/help.rst
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/requestreference.rst
  readme.md
  setup.py
  vvspy/__init__.py
  vvspy/arrivals.py
  vvspy/departures.py
  vvspy/obj/__init__.py
  vvspy/obj/arrival.py
  vvspy/obj/connection.py
  vvspy/obj/departure.py
  vvspy/obj/destination.py
  vvspy/obj/line_operator.py
  vvspy/obj/origin.py
  vvspy/obj/serving_line.py
  vvspy/obj/transportation.py
  vvspy/obj/trip.py
  vvspy/trip.py
Labels: documentation

#38 Zaanposni patch 1
  docs/source/introduction.rst
  vvspy/arrivals.py
  vvspy/departures.py
  vvspy/trip.py
Labels: documentation

#39 fixed codeblock
  docs/source/introduction.rst
Labels: documentation

#40 Feature/unittests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/workflows/unittests.yml
  .github/workflows/unittests_master.yml
  readme.md
  tests/mock_results/arrival_request_200.json
  tests/mock_results/arrival_request_400.json
  tests/mock_results/departure_request_200.json
  tests/mock_results/departure_request_400.json
  tests/mock_results/trip_request_200.json
  tests/mock_results/trip_request_400.json
  tests/start.py
  tests/unittests/__init__.py
  tests/unittests/parser.py
  vvspy/arrivals.py
  vvspy/obj/trip.py
Labels: documentation, github, unittests

#41 fixed master tests
  .github/workflows/unittests_master.yml
Labels: breaking, github

#42 added examples
  examples/check_delays_on_trip.py
  examples/display_of_incoming_departures.py
  vvspy/obj/serving_line.py
Labels: breaking, documentation

#43 bump versions
  docs/source/conf.py
  setup.py
Labels: documentation

#44 added vvstracker to example project
  readme.md
Labels: documentation

#46 added function to get only on result obj
  docs/source/conf.py
  docs/source/requestreference.rst
  setup.py
  tests/run_tests.bat
  tests/run_tests.sh
  vvspy/__init__.py
Labels: documentation, feature

#47 added option to get response obj of api request returned. fixes #…
  vvspy/__init__.py
  vvspy/arrivals.py
  vvspy/departures.py
  vvspy/trip.py
Labels: feature

#48 added reference for station id lookup to readme
  readme.md
Labels: documentation

#49 reference to get_trip / get_trips difference
  docs/source/conf.py
  readme.md
  setup.py
Labels: documentation
